# Generated by Django 2.0.2 on 2018-12-09 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchStock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(verbose_name='price date')),
                ('price_open', models.FloatField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_close', models.FloatField()),
                ('price_adj_close', models.FloatField()),
                ('price_volume', models.FloatField()),
                ('stock_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchStock.Stock')),
            ],
        ),
    ]
