# Generated by Django 2.1.4 on 2018-12-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchStock', '0002_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_average', models.FloatField()),
                ('predict_final', models.FloatField()),
                ('predict_median', models.FloatField()),
                ('predict_unreliable', models.IntegerField()),
                ('predict_std', models.FloatField()),
                ('stock_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchStock.Stock')),
            ],
        ),
    ]
